- name: Ignore ICMP redirects
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_file: /etc/sysctl.d/60-blindagem.conf
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
  tags: [net.accept_redirects, net]
