"""Build an Ansible playbook from the checks that failed.

The audit never changes anything; this is the separate, reviewable artifact an
administrator reads before applying. Only checks with a task file in ``tasks/``
can be automated — removing a UID 0 account or clearing a SUID bit is too risky
to generate, so those stay in the report as manual work.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from ..models import Report, Status

TASKS_DIR = Path(__file__).parent / "tasks"

HEADER = """\
# Generated by blindagem {version} from the audit of {hostname} at {generated_at}.
# Review it before applying. Suggested order:
#   ansible-playbook -i <host>, {name} --check --diff
#   ansible-playbook -i <host>, {name} --tags <check id or category>
#
# Requires: ansible.posix and community.general (see requirements.yml).
"""

PLAYBOOK_PREAMBLE = """\
- name: Blindagem remediation
  hosts: all
  become: true

  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
        state: restarted
      # Containers and images have no service manager to restart.
      when: not (skip_service_restart | default(false))

  tasks:
"""

# Runs before anything that could cut off the administrator's own session.
LOCKOUT_GUARD = """\
    - name: Safety check - a usable SSH key must exist before tightening SSH
      ansible.builtin.stat:
        path: "{{ blindagem_authorized_keys | default('/root/.ssh/authorized_keys') }}"
      register: blindagem_keys
      tags: [always]

    - name: Refuse to lock the administrator out
      ansible.builtin.assert:
        that:
          - blindagem_keys.stat.exists
          - blindagem_keys.stat.size | default(0) > 0
        fail_msg: >-
          No authorized_keys found at
          {{ blindagem_authorized_keys | default('/root/.ssh/authorized_keys') }}.
          Install your public key first, or pass -e blindagem_allow_lockout=true
          if you are sure you have console access.
      when: not (blindagem_allow_lockout | default(false))
      tags: [always]

"""

#: Checks whose fix can cut off access, so the guard above must run first.
LOCKOUT_RISKY = {"ssh.password_auth", "ssh.root_login", "net.firewall_active"}

REQUIREMENTS = """\
---
collections:
  - name: ansible.posix     # sysctl module
  - name: community.general  # ufw module
"""


def available_tasks() -> set[str]:
    """Check ids that have an automated fix."""
    return {path.stem for path in TASKS_DIR.glob("*.yml")}


def failing_checks(report: Report) -> list[str]:
    """Ids of checks that failed (or warned) and were not accepted, worst first."""
    order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    rows = [
        (order.get(report.meta[r.check_id].severity.value, 9), r.check_id)
        for r in report.results
        if r.status in (Status.FAIL, Status.WARN) and not r.accepted and r.check_id in report.meta
    ]
    return [check_id for _, check_id in sorted(rows)]


def build(report: Report) -> tuple[str, list[str], list[str]]:
    """Return ``(playbook_yaml, automated_ids, manual_ids)``."""
    have = available_tasks()
    failing = failing_checks(report)
    automated = [check_id for check_id in failing if check_id in have]
    manual = [check_id for check_id in failing if check_id not in have]

    body = []
    if any(check_id in LOCKOUT_RISKY for check_id in automated):
        body.append(LOCKOUT_GUARD)
    for check_id in automated:
        body.append(_indent((TASKS_DIR / f"{check_id}.yml").read_text().rstrip("\n")))
        body.append("")

    if not automated:
        body.append(
            "    - name: Nothing to automate - every finding needs a manual decision\n"
            "      ansible.builtin.debug:\n"
            "        msg: see the blindagem report for the manual steps\n"
            "      tags: [always]\n"
        )

    header = HEADER.format(
        version=report.tool_version,
        hostname=report.host.hostname,
        generated_at=report.generated_at,
        name="fix.yml",
    )
    manual_notes = ""
    if manual:
        lines = ["#", "# Left for you to do by hand (too risky to generate):"]
        for check_id in manual:
            # Wrapped because a comment over 160 characters trips ansible-lint.
            wrapped = textwrap.wrap(f"{check_id}: {report.meta[check_id].remediation}", width=92)
            lines.append(f"#   - {wrapped[0]}")
            lines.extend(f"#     {line}" for line in wrapped[1:])
        manual_notes = "\n".join(lines) + "\n"
    return header + manual_notes + "\n" + PLAYBOOK_PREAMBLE + "\n".join(body), automated, manual


def _indent(text: str, spaces: int = 4) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


def write(report: Report, path: str | Path) -> tuple[Path, list[str], list[str]]:
    playbook, automated, manual = build(report)
    destination = Path(path)
    destination.write_text(playbook, encoding="utf-8")
    (destination.parent / "requirements.yml").write_text(REQUIREMENTS, encoding="utf-8")
    return destination, automated, manual
